import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./ui/layout/header";
import Footer from "./ui/layout/footer";
import { ReduxProvider } from "./libs/stores/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
            <ReduxProvider>
                <Header />
                {children}
                <Footer />
            </ReduxProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
